# DATA CLEANING STEP 1

## The aim of this step is to fill any blank values in the global_power_plant_database.csv file and to convert it into a text format that can be then inserted into the SQL table.

## IMPORTING NECESSARY LIBRARIES

In [2]:
import pandas as pd
import numpy as np

## IMPORTING DATA

In [3]:
A = pd.read_csv("global_power_plant_database.csv", low_memory = False)

In [4]:
A

,country,country_long,name,gppd_idnr,capacity_mw,latitude,longitude,primary_fuel,other_fuel1,other_fuel2,...,estimated_generation_gwh_2013,estimated_generation_gwh_2014,estimated_generation_gwh_2015,estimated_generation_gwh_2016,estimated_generation_gwh_2017,estimated_generation_note_2013,estimated_generation_note_2014,estimated_generation_note_2015,estimated_generation_note_2016,estimated_generation_note_2017
0,AFG,Afghanistan,Kajaki Hydroelectric Power Plant Afghanistan,GEODB0040538,33.0,32.3220,65.1190,Hydro,NaN,NaN,...,123.77,162.90,97.39,137.76,119.50,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1
1,AFG,Afghanistan,Kandahar DOG,WKS0070144,10.0,31.6700,65.7950,Solar,NaN,NaN,...,18.43,17.48,18.25,17.70,18.29,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE
2,AFG,Afghanistan,Kandahar JOL,WKS0071196,10.0,31.6230,65.7920,Solar,NaN,NaN,...,18.64,17.58,19.10,17.62,18.72,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE,SOLAR-V1-NO-AGE
3,AFG,Afghanistan,Mahipar Hydroelectric Power Plant Afghanistan,GEODB0040541,66.0,34.5560,69.4787,Hydro,NaN,NaN,...,225.06,203.55,146.90,230.18,174.91,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1
4,AFG,Afghanistan,Naghlu Dam Hydroelectric Power Plant Afghanistan,GEODB0040534,100.0,34.6410,69.7170,Hydro,NaN,NaN,...,406.16,357.22,270.99,395.38,350.80,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34931,ZMB,Zambia,Ndola,WRI1022386,50.0,-12.9667,28.6333,Oil,NaN,NaN,...,NaN,NaN,NaN,NaN,183.79,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,CAPACITY-FACTOR-V1
34932,ZMB,Zambia,Nkana,WRI1022384,20.0,-12.8167,28.2000,Oil,NaN,NaN,...,NaN,NaN,NaN,NaN,73.51,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,CAPACITY-FACTOR-V1
34933,ZMB,Zambia,Victoria Falls,WRI1022380,108.0,-17.9167,25.8500,Hydro,NaN,NaN,...,575.78,575.78,548.94,579.90,578.32,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1
34934,ZWE,Zimbabwe,Hwange Coal Power Plant Zimbabwe,GEODB0040404,920.0,-18.3835,26.4700,Coal,NaN,NaN,...,NaN,NaN,NaN,NaN,2785.10,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,NO-ESTIMATION,CAPACITY-FACTOR-V1
34935,ZWE,Zimbabwe,Kariba Dam South Hydroelectric Power Station Z...,GEODB0003803,750.0,-16.5222,28.7619,Hydro,NaN,NaN,...,3999.75,3999.75,3745.02,3428.65,3960.24,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1,HYDRO-V1

## DATA CLEANING

### Deleting unnesessary columns

In [5]:
cols = ["country", "latitude", "longitude", "other_fuel1", "other_fuel2", "other_fuel3", "owner"
       , "source", "url", "geolocation_source", "wepp_id", "year_of_capacity_data", "generation_gwh_2013",
          "generation_gwh_2014", "generation_gwh_2015", "generation_gwh_2016", "generation_gwh_2017",
          "generation_gwh_2018", "generation_gwh_2019", "generation_data_source", "estimated_generation_note_2013",
          "estimated_generation_note_2014", "estimated_generation_note_2015", "estimated_generation_note_2016",
          "estimated_generation_note_2017"]
A.drop(cols, inplace = True, axis = 1)

In [6]:
A

,country_long,name,gppd_idnr,capacity_mw,primary_fuel,commissioning_year,estimated_generation_gwh_2013,estimated_generation_gwh_2014,estimated_generation_gwh_2015,estimated_generation_gwh_2016,estimated_generation_gwh_2017
0,Afghanistan,Kajaki Hydroelectric Power Plant Afghanistan,GEODB0040538,33.0,Hydro,NaN,123.77,162.90,97.39,137.76,119.50
1,Afghanistan,Kandahar DOG,WKS0070144,10.0,Solar,NaN,18.43,17.48,18.25,17.70,18.29
2,Afghanistan,Kandahar JOL,WKS0071196,10.0,Solar,NaN,18.64,17.58,19.10,17.62,18.72
3,Afghanistan,Mahipar Hydroelectric Power Plant Afghanistan,GEODB0040541,66.0,Hydro,NaN,225.06,203.55,146.90,230.18,174.91
4,Afghanistan,Naghlu Dam Hydroelectric Power Plant Afghanistan,GEODB0040534,100.0,Hydro,NaN,406.16,357.22,270.99,395.38,350.80
...,...,...,...,...,...,...,...,...,...,...,...
34931,Zambia,Ndola,WRI1022386,50.0,Oil,NaN,NaN,NaN,NaN,NaN,183.79
34932,Zambia,Nkana,WRI1022384,20.0,Oil,NaN,NaN,NaN,NaN,NaN,73.51
34933,Zambia,Victoria Falls,WRI1022380,108.0,Hydro,NaN,575.78,575.78,548.94,579.90,578.32
34934,Zimbabwe,Hwange Coal Power Plant Zimbabwe,GEODB0040404,920.0,Coal,NaN,NaN,NaN,NaN,NaN,2785.10
34935,Zimbabwe,Kariba Dam South Hydroelectric Power Station Z...,GEODB0003803,750.0,Hydro,NaN,3999.75,3999.75,3745.02,3428.65,3960.24

### Filling blank spaces

In [7]:
A.fillna(value = 0, inplace = True)
A

,country_long,name,gppd_idnr,capacity_mw,primary_fuel,commissioning_year,estimated_generation_gwh_2013,estimated_generation_gwh_2014,estimated_generation_gwh_2015,estimated_generation_gwh_2016,estimated_generation_gwh_2017
0,Afghanistan,Kajaki Hydroelectric Power Plant Afghanistan,GEODB0040538,33.0,Hydro,0.0,123.77,162.90,97.39,137.76,119.50
1,Afghanistan,Kandahar DOG,WKS0070144,10.0,Solar,0.0,18.43,17.48,18.25,17.70,18.29
2,Afghanistan,Kandahar JOL,WKS0071196,10.0,Solar,0.0,18.64,17.58,19.10,17.62,18.72
3,Afghanistan,Mahipar Hydroelectric Power Plant Afghanistan,GEODB0040541,66.0,Hydro,0.0,225.06,203.55,146.90,230.18,174.91
4,Afghanistan,Naghlu Dam Hydroelectric Power Plant Afghanistan,GEODB0040534,100.0,Hydro,0.0,406.16,357.22,270.99,395.38,350.80
...,...,...,...,...,...,...,...,...,...,...,...
34931,Zambia,Ndola,WRI1022386,50.0,Oil,0.0,0.00,0.00,0.00,0.00,183.79
34932,Zambia,Nkana,WRI1022384,20.0,Oil,0.0,0.00,0.00,0.00,0.00,73.51
34933,Zambia,Victoria Falls,WRI1022380,108.0,Hydro,0.0,575.78,575.78,548.94,579.90,578.32
34934,Zimbabwe,Hwange Coal Power Plant Zimbabwe,GEODB0040404,920.0,Coal,0.0,0.00,0.00,0.00,0.00,2785.10
34935,Zimbabwe,Kariba Dam South Hydroelectric Power Station Z...,GEODB0003803,750.0,Hydro,0.0,3999.75,3999.75,3745.02,3428.65,3960.24

### Converting all the values in the dataframe to strings

In [8]:
A = A.astype("string")

In [9]:
A.dtypes

country_long                     string[python]
name                             string[python]
gppd_idnr                        string[python]
capacity_mw                      string[python]
primary_fuel                     string[python]
commissioning_year               string[python]
estimated_generation_gwh_2013    string[python]
estimated_generation_gwh_2014    string[python]
estimated_generation_gwh_2015    string[python]
estimated_generation_gwh_2016    string[python]
estimated_generation_gwh_2017    string[python]
dtype: object

## CONVERTING THE DATAFRAME TO A TEXT FILE

### Converting the data frame to a list of tuples.

In [10]:
Y = []
for i in range(len(A)):
    x = tuple(A.iloc[i])
    Y.append(x)

In [11]:
Y[9090]

('China',
 'Yunnan Langgeluohe',
 'WRI1071950',
 '12.0',
 'Hydro',
 '0.0',
 '27.42',
 '36.89',
 '36.89',
 '42.66',
 '36.89')

### Writing the contents on to a text file

In [12]:
file = open("power_plants1", "w", encoding = "utf-8")
for jock in Y:
    file.write(str(jock) + "," + "\n")
file.close()